import {
  filterPublishableEvents,
  isInDateRange,
  mergeDuplicateEvents,
  toShanghaiDayWindow,
} from "./events.js";
import { defaultFetchHtml } from "./fetch-html.js";
import { checkRobots } from "./robots.js";
import { PARSERS } from "./parsers/index.js";
import { isRelevantPerformance } from "./parsers/shared.js";

export { defaultFetchHtml } from "./fetch-html.js";
export { parseJsonLdEvents } from "./parsers/json-ld.js";

export const SOURCE_SEEDS_RAW = [
  // 秀动上海：整站 JS 渲染，h5 网络不可达，API 需签名（2026-08 探明），待逆向后恢复：
  // { name: "秀动上海", url: "https://www.showstart.com/event/list?cityCode=310000", category: "演出音乐", locale: "zh", parser: PARSERS.showstart },
  {
    name: "豆瓣同城上海",
    url: "https://www.douban.com/location/shanghai/events",
    category: "演出音乐",
    locale: "zh",
    parser: PARSERS.douban,
  },
  {
    name: "SmartShanghai Events",
    url: "https://www.smartshanghai.com/events/",
    category: "演出音乐",
    locale: "en",
    parser: PARSERS.smartshanghai,
  },
  {
    name: "SmartShanghai Live Music",
    url: "https://www.smartshanghai.com/events/?category=live-music",
    category: "演出音乐",
    locale: "en",
    parser: PARSERS.smartshanghai,
  },
  { name: "AllEvents Shanghai", url: "https://allevents.in/shanghai", category: "演出音乐", locale: "en", parser: PARSERS.allevents },
  {
    name: "Eventbrite Shanghai Music",
    url: "https://www.eventbrite.com/d/china--shanghai/music--events/",
    category: "演出音乐",
    locale: "en",
    parser: PARSERS.tentimes,
  },
  {
    name: "复星艺术中心",
    url: "https://www.fosunfoundation.com/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.fosun,
  },
  {
    name: "上海外滩美术馆",
    url: "https://www.rockbundartmuseum.org/exhibitions/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.rockbund,
  },
  {
    name: "teamLab 无界上海",
    url: "https://art.team-lab.cn/e/borderless-shanghai/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.teamlab,
  },
  // 上海当代艺术博物馆（PSA）：整站 JS 渲染无 API；其展览已被 iMuseum 聚合源覆盖（2026-08 验证）
  {
    name: "中华艺术宫",
    url: "https://www.artmuseumonline.org/art/art/zlgz/zl/dqzl/index.html",
    category: "展览",
    locale: "zh",
    parser: PARSERS.chinaArtMuseum,
  },
  {
    name: "浦东美术馆",
    url: "https://www.museumofartpd.org.cn/exhibition",
    category: "展览",
    locale: "zh",
    parser: PARSERS.map,
  },
  {
    name: "UCCA Edge 上海",
    url: "https://ucca.org.cn/exhibitions/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.ucca,
  },
  {
    name: "Fotografiska 上海",
    url: "https://shanghai.fotografiska.com/en/whats-on",
    category: "展览",
    locale: "zh",
    parser: PARSERS.fotografiska,
  },
  {
    name: "iMuseum 上海展览",
    url: "https://art.icity.ly/shanghai",
    category: "展览",
    locale: "zh",
    parser: PARSERS.imuseum,
    notes: "每日环球展览 iMuseum · 聚合上海各场馆展览信息",
  },
  {
    name: "上海民生现代美术馆",
    url: "http://www.minshengart.com/cn/index/exhibitions-and-events/exhibition",
    category: "展览",
    locale: "zh",
    parser: PARSERS.minsheng,
    notes: "民生现代美术馆 · 当代艺术展览",
  },
  {
    name: "宝龙美术馆·正在热展",
    url: "https://www.powerlongmuseum.com/exhibition_now.html",
    category: "展览",
    locale: "zh",
    parser: PARSERS.powerlong,
    notes: "宝龙美术馆·正在热展 · 列表含展期与展厅（2026-10 验证）",
  },
  {
    name: "宝龙美术馆·即将到来",
    url: "https://www.powerlongmuseum.com/exhibition_future.html",
    category: "展览",
    locale: "zh",
    parser: PARSERS.powerlong,
    notes: "宝龙美术馆·即将到来 · 新展预告（2026-10 验证）",
  },
  {
    name: "意大利文化处·活动日历",
    url: "https://iicshanghai.esteri.it/zh/gli_eventi/calendario/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.iicShanghai,
    notes: "意大利驻沪总领馆文化处 · 意方相关展览/文化活动（多在上海各美术馆）（2026-10 验证）",
  },
  {
    name: "龙美术馆",
    url: "http://www.thelongmuseum.org/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.longMuseum,
    notes: "龙美术馆西岸馆 · 当代艺术展览",
  },
  {
    name: "余德耀美术馆",
    url: "http://www.yuzmshanghai.org/exhibitions/current/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.yuzMuseum,
    notes: "余德耀美术馆 · 当代艺术展览",
  },
  {
    name: "震旦博物馆",
    url: "https://www.auroramuseum.cn/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.auroraMuseum,
    notes: "震旦博物馆 · 古代文物与当代艺术",
  },
  {
    name: "上海博物馆",
    url: "https://www.shanghaimuseum.net/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.shanghaiMuseum,
    notes: "上海博物馆 · 文物考古与艺术展览",
  },
  {
    name: "西岸美术馆",
    url: "http://wbmshanghai.com/zh-hans/exhibition/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.westbundMuseum,
    notes: "西岸美术馆 · 蓬皮杜中心合作项目",
  },
  {
    name: "苏州博物馆",
    url: "https://www.szmuseum.com/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.szmuseum,
    notes: "苏州博物馆 · 长三角周边展览",
  },
  // 西岸艺博会：整站 JS 渲染无 API（2026-08 探明）
  // 本地宝系（活动/周末/市集/音乐演出/演唱会/商场快闪/展览/展会）：拼图验证码反爬，7 源全挂（2026-08 验证）；
  // 公众号类内容改走 wechat-exporter 管线（WECHAT_EVENTS_API_URL）
  {
    name: "上海文化广场",
    url: "https://www.shcstheatre.com/Program/ProgramList.aspx",
    category: "演出音乐",
    locale: "zh",
    parser: PARSERS.shcstheatre,
    notes: "音乐剧、话剧、音乐会演出排期",
  },
  {
    name: "上海音乐学院·海报墙",
    url: "https://www.shcmusic.edu.cn/xhdrl/list.htm",
    category: "演出音乐",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海音乐学院",
    defaultVenue: "上海音乐学院",
    notes: "上音·海报墙 · 音乐会/演出预告（标题含演出日期）（2026-10 验证）",
  },
  {
    name: "上海戏剧学院·活动信息",
    url: "https://www.sta.edu.cn/hdxx/list.htm",
    category: "演出音乐",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海戏剧学院",
    defaultVenue: "上海戏剧学院",
    notes: "上戏·活动信息 · 话剧/展映/大师班（2026-10 验证）",
  },
  {
    name: "格瓦拉",
    url: "https://www.gewara.com/",
    category: "演出音乐",
    locale: "zh",
    parser: PARSERS.gewara,
    notes: "电影/演出票务 · 上海站",
  },
  {
    name: "票牛",
    url: "https://www.piaoniu.com/",
    category: "演出音乐",
    locale: "zh",
    parser: PARSERS.piaoniu,
    notes: "演唱会/音乐会/话剧/体育赛事票务",
  },
  // 上海话剧艺术中心：API 仅剧目库无档期、页面无演出数据；售票信息已被格瓦拉覆盖（2026-08 验证）
  // 中国上海国际艺术节：整站 JS 渲染；参演剧目已被格瓦拉覆盖（2026-08 验证，样本含2条艺术节剧目）
  {
    name: "赢商网",
    url: "http://www.winshang.com/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.winshang,
    notes: "商业地产门户 · 新店开业/品牌首店资讯",
  },
  {
    name: "赢商网·华东",
    url: "http://sh.winshang.com/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.winshangShanghai,
    notes: "华东商业地产 · 上海项目招商/品牌入驻",
  },
  {
    name: "Timeout上海",
    url: "https://www.timeoutshanghai.com/",
    category: "线下活动",
    locale: "en",
    parser: PARSERS.timeoutShanghai,
    notes: "上海英文生活方式指南 · 活动/餐饮/艺术",
  },
  {
    name: "上海热线",
    url: "https://www.online.sh.cn/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.shanghaiOnline,
    notes: "上海本地门户 · 各类活动资讯",
  },
  // 上海群艺馆：整站 JS 渲染无 API（2026-08 探明）
  {
    name: "上海文旅局·艺术活动",
    url: "https://whlyj.sh.gov.cn/yshd/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.whlyj,
    notes: "上海市文旅局 · 月度美术馆观展指南/文化活动",
  },
  // 上海自然博物馆：整站 JS 渲染无 API（2026-08 探明）
  // 大麦上海：HTTP 500 反爬（2026-08 探明）；票务信息由格瓦拉/票牛覆盖
  {
    name: "活动行上海",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&orderby=hot",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "eventlist 端点为 SSR 渲染，events 页为 JS 渲染",
  },
  {
    name: "活动行·上海推荐",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "活动行上海默认推荐流（非热门排序）· 各行业活动（2026-10 验证）",
  },
  {
    name: "上海图书馆·活动预约",
    url: "https://www.library.sh.cn/activity",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.shlibActivity,
    notes: "上海图书馆·活动预约（全部分类）· 讲座/展览/培训（2026-10 验证）",
  },
  {
    name: "上海图书馆·讲座",
    url: "https://www.library.sh.cn/activity?tabName=%E8%AE%B2%E5%BA%A7",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.shlibActivity,
    notes: "上海图书馆·讲座 tab · 上图讲座系列（2026-10 验证）",
  },
  {
    name: "嘉定区图书馆·嘉图讲座",
    url: "http://wenlv.jiading.cn/jdlib/hd/jtjz",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.jiadingLibrary,
    notes: "嘉定区图书馆·嘉图讲座栏目 · 详情页补活动时间/地点（2026-10 验证）",
  },
  {
    name: "互动吧上海",
    url: "https://www.huodong.com/event?cityCode=310000",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.huodongBa,
  },
  {
    name: "Eventbrite Shanghai",
    url: "https://www.eventbrite.com/d/china--shanghai/events/",
    category: "线下活动",
    locale: "en",
    parser: PARSERS.tentimes,
  },
  {
    name: "Eventbrite Shanghai Business",
    url: "https://www.eventbrite.com/d/china--shanghai/business--events/",
    category: "线下活动",
    locale: "en",
    parser: PARSERS.tentimes,
  },
  {
    name: "Eventbrite Shanghai Networking",
    url: "https://www.eventbrite.com/d/china--shanghai/networking--events/",
    category: "线下活动",
    locale: "en",
    parser: PARSERS.tentimes,
  },
  { name: "Lu.ma Shanghai", url: "https://lu.ma/shanghai", category: "线下活动", locale: "en", parser: PARSERS.luma },
  { name: "NYU Shanghai Events", url: "https://events.shanghai.nyu.edu/", category: "高校讲座", locale: "en", parser: PARSERS.nyu },
  { name: "上外活动平台", url: "https://event.shisu.edu.cn/", category: "高校讲座", locale: "zh", parser: PARSERS.shisu },
  { name: "上海交通大学活动", url: "https://gc.sjtu.edu.cn/cn/event/", category: "高校讲座", locale: "zh", parser: PARSERS.sjtu },
  {
    name: "同济大学活动",
    url: "https://see.tongji.edu.cn/index/jqzyhd.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.tongjiSee,
  },
  {
    name: "上海财经大学",
    url: "https://www.sufe.edu.cn/",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.sufe,
    notes: "上海财经大学 · 学术讲座与校园活动",
  },
  {
    name: "华东师范大学主页讲座",
    url: "https://eoffice.ecnu.edu.cn/sublectures/main.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.ecnuLectures,
    notes: "华师大院系学术讲座荟萃 · SSR 列表 + 详情页结构化抓取",
  },
  {
    name: "复旦大学化学系讲座",
    url: "https://chemistry.fudan.edu.cn/46012/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.fudanChemistry,
    notes: "复旦化学系 · SSR 列表内含主讲/时间/地点",
  },
  {
    name: "上海交通大学学术讲座",
    url: "https://news.sjtu.edu.cn/xsjz/index.html",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.sjtuNewsLectures,
    notes: "上交新闻中心·学术讲座栏目 · SSR 列表内含时间/地点/主讲",
  },
  {
    name: "上海电力大学学术活动",
    url: "https://www.shiep.edu.cn/academics/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.shiepLectures,
    notes: "上海电力大学 · SSR 列表内含时间/地点/主讲/主办",
  },
  {
    name: "上海科技大学讲座报告",
    url: "https://www.shanghaitech.edu.cn/p15080c14750/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.shanghaitechLectures,
    notes: "上科大讲座报告 · SSR 列表 + 详情页取开始时间/报告地点",
  },
  {
    name: "华东理工大学讲座报告",
    url: "https://news.ecust.edu.cn/jzbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.ecustLectures,
    notes: "华东理工·讲座报告栏目 · 单页 24 条覆盖化学/生物/药学/经济多学科 · SSR 列表内含讲座时间/地点",
  },
  {
    name: "复旦大学上海医学院讲座",
    url: "https://gs-shmc.fudan.edu.cn/sywtz/list1.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.fudanShmcLectures,
    notes: "复旦上海医学院·最新动态中标识为［讲座信息］的条目 · 详情页为海报图故以发布日作为开始时间兜底",
  },
  {
    name: "复旦大学药学院讲座",
    url: "https://spfdu.fudan.edu.cn/28477/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.fudanSpfduLectures,
    notes: "复旦药学院·通知公告 · 按标题关键词（讲座/讲坛/论坛）过滤，标题内含日期则优先解析",
  },
  {
    name: "上海创智学院·创智日历",
    url: "https://www.sii.edu.cn/czrl/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.siiCalendar,
    notes: "AI 前沿学术报告/创智沙龙 · SSR 列表内含讲座时间与地点（2026-10 验证）",
  },
  // ===== 高校门户讲座栏目（同一套 CMS 模板，解析器见 cn-cms-lectures.js）=====
  {
    name: "上海师范大学·学术讲座",
    url: "https://www.shnu.edu.cn/xsxx/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海师范大学",
    defaultVenue: "上海师范大学",
    notes: "上师大·学术讲座栏目 · 列表日期为发布日，详情页补时间/地点（2026-10 验证）",
  },
  {
    name: "上海师范大学·活动演出",
    url: "https://www.shnu.edu.cn/hdyc/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海师范大学",
    defaultVenue: "上海师范大学",
    notes: "上师大·活动演出栏目 · 典礼/演出/校园活动（2026-10 验证）",
  },
  // 上师大·学术园地（xsxx1）：科研成果新闻栏目（论文进展/获奖），非活动预告，故不采集（2026-10 验证）
  {
    name: "华东政法大学·讲座",
    url: "https://www.ecupl.edu.cn/jz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "华东政法大学",
    defaultVenue: "华东政法大学",
    notes: "华政·讲座栏目 · 详情页含「时 间/地 点」字段（2026-10 验证）",
  },
  {
    name: "上海理工大学·讲座日志",
    url: "https://www.usst.edu.cn/jzrz2_1045/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学",
    defaultVenue: "上海理工大学",
    notes: "上理工·讲座日志 · 列表内联时间与地点，无需抓详情（2026-10 验证）",
  },
  {
    name: "上海理工大学·学术报告",
    url: "https://www.usst.edu.cn/xsbg_1583/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学",
    defaultVenue: "上海理工大学",
    notes: "上理工·学术报告栏目 · 列表内联时间与地点（2026-10 验证，栏目更新较慢）",
  },
  {
    name: "上海理工大学·文化活动",
    url: "https://www.usst.edu.cn/whhd_1584/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学",
    defaultVenue: "上海理工大学",
    notes: "上理工·文化活动栏目 · 讲坛/大师课等（2026-10 验证，栏目更新较慢）",
  },
  {
    name: "上海海事大学·讲座信息",
    url: "https://www.shmtu.edu.cn/xsjz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海海事大学",
    defaultVenue: "上海海事大学",
    notes: "海事·讲座信息栏目 · 含 AI/深度学习等前沿讲座（2026-10 验证）",
  },
  {
    name: "上海海事大学·学生活动",
    url: "https://www.shmtu.edu.cn/12204/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海海事大学",
    defaultVenue: "上海海事大学",
    notes: "海事·学生活动栏目 · 校园培训/实践动态（2026-10 验证）",
  },
  {
    name: "上海政法学院·学术星空",
    url: "https://www.shupl.edu.cn/xsxk/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海政法学院",
    defaultVenue: "上海政法学院",
    notes: "上政·学术星空栏目 · 讲坛/工作坊（2026-10 验证）",
  },
  {
    name: "上海健康医学院·讲座报告",
    url: "https://www.sumhs.edu.cn/jzbg_1326/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海健康医学院",
    defaultVenue: "上海健康医学院",
    notes: "上健医·讲座报告栏目 · 学术沙龙系列（2026-10 验证）",
  },
  {
    name: "上海海洋大学·学术讲座",
    url: "https://www.shou.edu.cn/xsjz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海海洋大学",
    defaultVenue: "上海海洋大学",
    notes: "上海海洋·学术讲座栏目 · 详情页补时间（2026-10 验证，栏目更新较慢）",
  },
  {
    // 通用 LLM 抽取源试点：自建站 /events 页有 Cloudflare 403，首页 SSR 可用
    name: "AI Tinkerers Shanghai",
    url: "https://shanghai.aitinkerers.org/",
    category: "AI聚会",
    locale: "en",
    parser: PARSERS.llmExtract,
    notes: "通用 LLM 抽取（需 LLM_EXTRACT_ENABLED）· 官网 shanghai.aitinkerers.org",
  },
  {
    name: "ShanghAI AI Meetup",
    url: "https://www.meetup.com/shanghai-ai/",
    category: "AI聚会",
    locale: "en",
    parser: PARSERS.meetup,
  },
  // OpenClaw Shanghai：与 Lu.ma Shanghai 同 URL（lu.ma/shanghai）重复，已删（2026-08 验证）
  {
    name: "Eventbrite Shanghai AI",
    url: "https://www.eventbrite.com/d/china--shanghai/artificial-intelligence--events/",
    category: "AI聚会",
    locale: "en",
    parser: PARSERS.eventbriteAiTech,
  },
  {
    name: "Eventbrite Shanghai Tech",
    url: "https://www.eventbrite.com/d/china--shanghai/science-and-tech--events/",
    category: "AI聚会",
    locale: "en",
    parser: PARSERS.eventbriteAiTech,
  },
  {
    name: "活动行·上海AI",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "活动行「人工智能」标签 · GAIC/PyCon/A2M 等上海 AI 大会与路演",
  },
  {
    name: "活动行·上海AI关键词",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=AI",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "活动行「AI」标签 · AI Engineer/具身智能/开发者大会（2026-10 验证）",
  },
  {
    name: "活动行·上海大模型",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E5%A4%A7%E6%A8%A1%E5%9E%8B",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "活动行「大模型」标签 · 模型/Agent 开发者线下活动（2026-10 验证）",
  },
  {
    name: "活动行·上海AIGC",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=AIGC",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "活动行「AIGC」标签 · AIGC 应用/训练营类活动（2026-10 验证）",
  },
  {
    name: "GDG 上海",
    url: "https://gdg.community.dev/gdg-shanghai/",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.gdgShanghai,
    notes: "Google 开发者社区上海 · Build with AI/DevFest/Gemma 大赛等（2026-10 验证）",
  },
  {
    name: "上海人工智能实验室·科研活动",
    url: "https://www.shlab.org.cn/event",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.shlab,
    notes: "上海AI实验室活动预告/论坛/交流会 · 列表标题 + 详情页限量取日期（2026-10 验证）",
  },

  // ===== 2026-10 第六批扩展：不限领域 bulk 扩容（西交利物浦/上科大/上音/上戏/电机/海关学院等院系 + 活动行演出类标签 + 会展/图书馆/美术馆/媒体）=====
  {
    name: "西交利物浦大学·讲座预告",
    url: "http://meeting.xjtu.edu.cn/lecturenotices/list/0/1",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 窗口内活跃 12/15（2026-10 验证）",
  },
  {
    name: "上海市政府·赛事活动",
    url: "https://www.shanghai.gov.cn/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·政府赛事 · 窗口内活跃 7/14（2026-10 验证）",
  },
  {
    name: "上科大信息学院·活动",
    url: "http://siais.shanghaitech.edu.cn/hd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 窗口内活跃 5/14（2026-10 验证）",
  },
  {
    name: "上科大信息学院·学术通知",
    url: "http://siais.shanghaitech.edu.cn/tzgg_6160/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 窗口内活跃 5/14（2026-10 验证）",
  },
  {
    name: "上海海洋大学·通知公告",
    url: "http://www.shou.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 窗口内活跃 5/12（2026-10 验证）",
  },
  {
    name: "上海中医药大学·活动剪影",
    url: "http://iec.shutcm.edu.cn/hdly/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 窗口内活跃 2/24（2026-10 验证）",
  },
  {
    name: "上海新国际博览中心·展会",
    url: "https://www.sniec.net/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·会展 · 窗口内活跃 2/6（2026-10 验证）",
  },
  {
    name: "SegmentFault",
    url: "https://segmentfault.com/events",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·场馆 · 窗口内活跃 1/24（2026-10 验证）",
  },
  {
    name: "上海电机学院·通知公告",
    url: "http://wgyxy.sdju.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 窗口内活跃 1/12（2026-10 验证）",
  },
  {
    name: "上科大创业学院·活动",
    url: "https://cue.shanghaitech.edu.cn/hdActivities1/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 窗口内活跃 1/11（2026-10 验证）",
  },
  {
    name: "钛媒体·活动",
    url: "https://www.tmtpost.com/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·科技媒体 · 窗口内活跃 1/11（2026-10 验证）",
  },
  {
    name: "上经贸大·学术讲座",
    url: "https://www.suibe.edu.cn/kjxy/1308/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 15 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上应技大研究生院·学术交流",
    url: "https://gs.sit.edu.cn/pygz/xsjl/xsjz.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 15 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上经贸大·会展学院学术活动",
    url: "http://www.suibe.edu.cn/sis/xshd_22034/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 14 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海海关学院·管理学院科研",
    url: "https://gsgl.shcc.edu.cn/kxyj/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 14 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海戏剧学院·创意论坛",
    url: "https://cyxy.sta.edu.cn/547/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 14 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海电机学院·学院通知",
    url: "https://xyh.sdju.edu.cn/jzxx/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 12 条，近期无更新（2026-10 验证）",
  },
  {
    name: "静安区图书馆·活动",
    url: "https://www.jingan.gov.cn/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·图书馆 · 已验证栏目 12 条，近期无更新（2026-10 验证）",
  },
  {
    name: "复旦大学研究生院·学术活动",
    url: "https://gsao.fudan.edu.cn/",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 10 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海戏剧学院·文学系活动",
    url: "https://wmzx.sta.edu.cn/hdxx/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 8 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海海事大学·国际交流讲座",
    url: "https://smuiec.shmtu.edu.cn/7015/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 8 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海戏剧学院·艺术管理论坛",
    url: "https://cyxy.sta.edu.cn/571/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 8 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海音乐学院·学术论坛",
    url: "https://yjsb.shcmusic.edu.cn/158/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 8 条，近期无更新（2026-10 验证）",
  },
  {
    name: "二工大jxxy·活动预告",
    url: "http://jxxy.sspu.edu.cn/2085/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 7 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海电机学院·高工学院通知",
    url: "http://gzxy.sdju.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 6 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海海关学院·外语学院科研",
    url: "https://wyx.shcc.edu.cn/kxyj/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 6 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海戏剧学院·讲座信息",
    url: "https://xw.sta.edu.cn/4261/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 6 条，近期无更新（2026-10 验证）",
  },
  {
    name: "奉贤图书馆·活动",
    url: "https://www.fxlib.cn/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·图书馆 · 已验证栏目 6 条，近期无更新（2026-10 验证）",
  },
  {
    name: "InfoQ 中文站·活动",
    url: "https://www.infoq.cn/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.listing,
    notes: "第六批·科技媒体 · 已验证栏目 6 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海对外经贸大学·更多>>",
    url: "http://mba.suibe.edu.cn/hdtg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 5 条，近期无更新（2026-10 验证）",
  },
  {
    name: "二工大·旧站通知",
    url: "http://oldhome.sspu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 5 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海海洋大学·热门活动",
    url: "https://xszx.shou.edu.cn/hd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 5 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上经贸大·会展学院通知",
    url: "http://www.suibe.edu.cn/sis/tzgg_22036/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 4 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海戏剧学院·基础部通知",
    url: "http://jjy.sta.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 4 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海音乐学院·艺术学知识体系论坛",
    url: "https://www.shcmusic.edu.cn/gjzgzzdysxzstxlt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 4 条，近期无更新（2026-10 验证）",
  },
  {
    name: "复旦大学教务处·通知",
    url: "https://jwc.fudan.edu.cn/",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.listing,
    notes: "第六批·高校 · 已验证栏目 4 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上科大创业学院·科研动态",
    url: "https://cue.shanghaitech.edu.cn/kxyj/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 3 条，近期无更新（2026-10 验证）",
  },
  {
    name: "豆瓣同城·travel",
    url: "https://www.douban.com/location/shanghai/events/week-travel",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.douban,
    notes: "第六批·豆瓣 · 已验证栏目 3 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海海昌海洋公园·活动",
    url: "https://www.shhcoceanpark.com/",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·亲子 · 已验证栏目 3 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海海关学院·公共卫生学院通知",
    url: "https://ggjj.shcc.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 2 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海音乐学院·学生活动预告",
    url: "https://xsc.shcmusic.edu.cn/329/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 2 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海音乐学院·论坛与会议",
    url: "https://yjsb.shcmusic.edu.cn/102/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 2 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海音乐学院·作曲理论高峰论坛",
    url: "https://yjsb.shcmusic.edu.cn/213/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 2 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海交通大学研究生院·招生活动",
    url: "https://yzb.sjtu.edu.cn/",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 2 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上海电机学院·智能制造学术讲座",
    url: "https://aist.sdju.edu.cn/xytskc/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·高校 · 已验证栏目 1 条，近期无更新（2026-10 验证）",
  },
  {
    name: "国家会展中心上海·展会",
    url: "https://www.neccsh.com/",
    category: "展览",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第六批·会展 · 已验证栏目 1 条，近期无更新（2026-10 验证）",
  },

  // ===== 2026-10 AI 扩容：高校 AI/计算机/数据科学院系讲座栏目 + 活动行 AI 新标签 =====
  {
    name: "华师数据学院·学术报告",
    url: "https://dase.ecnu.edu.cn/xsbg/list.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·华东师大·数据科学与工程学院学术报告栏目 · 近期列入多条 AI/向量检索/多模态报告，最近更新 2026-09（2026-10 验证）",
  },
  {
    name: "复旦智能材料学院·讲座论坛",
    url: "http://icome.fudan.edu.cn/49264/list.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·复旦·智能材料与未来能源创新学院讲座论坛栏目 · 量子电子/热电/水凝胶等方向报告，最近更新 2026-09（2026-10 验证）",
  },
  {
    name: "复旦智能材料学院·通知公告",
    url: "http://icome.fudan.edu.cn/49262/list.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·复旦·智能材料与未来能源创新学院通知公告 · 含讲座预告与院所通知，最近更新 2026-09（2026-10 验证）",
  },
  {
    name: "上大计算机学院·学术活动",
    url: "https://cs.shu.edu.cn/index/xshd.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·上大·计算机学院学术活动栏目 · 已验证栏目 2 条，近期无更新（2026-10 验证）",
  },
  {
    name: "复旦软件学院·通知公告",
    url: "http://software.fudan.edu.cn/29333/list.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·复旦·软件学院通知公告栏目 · 已验证栏目 9 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上大人工智能研究院·学术活动",
    url: "https://ai.shu.edu.cn/kxyj/xshd.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·上大·人工智能研究院学术活动栏目 · 已验证栏目 6 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上大人工智能研究院·通知公告",
    url: "https://ai.shu.edu.cn/xwtz/tzgg.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·上大·人工智能研究院新闻通知 · 已验证栏目 9 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上大人工智能研究院·学院通知",
    url: "https://ai.shu.edu.cn/tzgg.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·上大·人工智能研究院学院通知 · 已验证栏目 6 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上科大信息学院·通知公告",
    url: "https://sist.shanghaitech.edu.cn/2863/list.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·上科大·信息学院通知公告栏目 · 已验证栏目 5 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上科大信息学院·通知公告(院办)",
    url: "https://sist.shanghaitech.edu.cn/tzgg/list.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·上科大·信息学院院办通知公告 · 已验证栏目 3 条，近期无更新（2026-10 验证）",
  },
  {
    name: "上科大信息学院·青年论坛",
    url: "https://sist.shanghaitech.edu.cn/qnlt/list.htm",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "AI 扩容·上科大·信息学院青年论坛 · 已验证栏目 3 条，近期无更新（2026-10 验证）",
  },
  {
    name: "活动行·上海Agent",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=Agent",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "AI 扩容·活动行「Agent」标签 · Agent/智能体方向上海活动 · 窗口内活跃 2/10（2026-10 验证）",
  },
  {
    name: "活动行·上海具身智能",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E5%85%B7%E8%BA%AB%E6%99%BA%E8%83%BD",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "AI 扩容·活动行「具身智能」标签 · 具身智能/机器人方向活动 · 窗口内活跃 2/10（2026-10 验证）",
  },
  {
    name: "活动行·上海智能体",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E6%99%BA%E8%83%BD%E4%BD%93",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "AI 扩容·活动行「智能体」标签 · Search/Deep Research 等 AI 沙龙，窗口内 1/8（2026-10 验证）",
  },
  {
    name: "Eventbrite 上海数据科学",
    url: "https://www.eventbrite.com/d/china--shanghai/data-science--events/",
    category: "AI聚会",
    locale: "en",
    parser: PARSERS.eventbriteAiTech,
    notes: "AI 扩容·Eventbrite 上海数据科学类活动 · 近期 6 条，当前窗口无条目（2026-10 验证）",
  },
  {
    name: "活动行·上海智能制造",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E6%99%BA%E8%83%BD%E5%88%B6%E9%80%A0",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "AI 扩容·活动行「智能制造」标签 · 制造业AI/工业具身智能/工业互联网类上海大会，窗口内 5/9（2026-10 验证）",
  },
  {
    name: "活动行·上海工业互联网",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E5%B7%A5%E4%B8%9A%E4%BA%92%E8%81%94%E7%BD%91",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "AI 扩容·活动行「工业互联网」标签 · 数智技术与工业场景撮合活动，窗口内 1/2（2026-10 验证）",
  },
  {
    name: "活动行·上海AI应用",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=AI%E5%BA%94%E7%94%A8",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "AI 扩容·活动行「AI应用」标签 · AI 应用/投融资路演类活动，窗口内 1/3（2026-10 验证）",
  },

  // ===== 2026-10 扩展：高校院系讲座栏目（cn-cms-lectures 通用模板 + <li>/锚点兜底扫描器）=====
  {
    name: "上海理工大学·基础学院讲座活动",
    url: "http://jcxb.usst.edu.cn/#container-2",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学基础学院",
    defaultVenue: "上海理工大学基础学院",
    notes: "上理工基础学院·讲座活动栏目 · 更新频繁，单次召回量居新增源之首（2026-10 验证）",
  },
  {
    name: "上海交通大学·机械动力工程学院学术报告",
    url: "https://me.sjtu.edu.cn/xsbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海交通大学机械与动力工程学院",
    defaultVenue: "上海交通大学机械与动力工程学院",
    notes: "上交机动学院·学术报告 · 列表内联日期（2026-10 验证）",
  },
  {
    name: "复旦大学·历史学系学术讲座",
    url: "https://history.fudan.edu.cn/xsky/xshd.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学历史学系",
    defaultVenue: "复旦大学历史学系",
    notes: "史学讲坛/讲座预告 · 列表内联日期（2026-10 验证）",
  },
  {
    name: "复旦大学·中文系讲座论坛",
    url: "http://chinese.fudan.edu.cn/jztg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学中文系",
    defaultVenue: "复旦大学中文系",
    notes: "复旦中文系·讲座/会议预告（文心、《文选》等）（2026-10 验证）",
  },
  {
    name: "复旦大学·化学系创建百年学术报告",
    url: "http://www.chemistry.fudan.edu.cn/52560/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学化学系",
    defaultVenue: "复旦大学化学系",
    notes: "创建百年系列学术报告 · 含哈佛/牛津/东南大学等主讲（2026-10 验证）",
  },
  {
    name: "复旦大学·外文学院学术活动",
    url: "https://dfll.fudan.edu.cn/27753/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学外国语言文学学院",
    defaultVenue: "复旦大学外国语言文学学院",
    notes: "各语种文学/语言学讲座（2026-10 验证）",
  },
  {
    name: "复旦大学·经济学院讲座会议预告",
    url: "https://econ.fudan.edu.cn/kxyj1/jzhyyg/xshy.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学经济学院",
    defaultVenue: "复旦大学经济学院",
    notes: "南土国际金融政策圆桌会等系列（2026-10 验证）",
  },
  {
    name: "复旦大学·数学科学学院实务讲座",
    url: "https://math.fudan.edu.cn/30390/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学数学科学学院",
    defaultVenue: "复旦大学数学科学学院",
    notes: "交叉与应用数学方向实务讲座（2026-10 验证）",
  },
  {
    name: "复旦大学·国际文化交流学院语言学沙龙",
    url: "http://www.ices.fudan.edu.cn/40361/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学国际文化交流学院",
    defaultVenue: "复旦大学国际文化交流学院",
    notes: "国交语言学沙龙系列 · 单学期多期（2026-10 验证）",
  },
  {
    name: "复旦大学·国务学院讲座论坛",
    url: "https://sirpa.fudan.edu.cn/35122/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学国际关系与公共事务学院",
    defaultVenue: "复旦大学国际关系与公共事务学院",
    notes: "政治学/公共管理讲座（2026-10 验证）",
  },
  {
    name: "华东政法大学·科研处学术讲坛",
    url: "http://kyc.ecupl.edu.cn/xsjt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "华东政法大学",
    defaultVenue: "华东政法大学",
    notes: "区域国别法/刑事审判等法学讲坛（2026-10 验证）",
  },
  {
    name: "华东师范大学·心理健康中心讲座",
    url: "http://xlzx.ecnu.edu.cn/6838/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "华东师范大学心理健康教育与咨询中心",
    defaultVenue: "华东师范大学心理健康教育与咨询中心",
    notes: "「青春密钥」面向公众的科普讲座（2026-10 验证）",
  },
  {
    name: "华东师范大学·图书馆文化活动",
    url: "http://lib.ecnu.edu.cn/whhd/list.htm",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "华东师范大学图书馆",
    defaultVenue: "华东师范大学图书馆",
    notes: "主题书展/阅读推广活动（2026-10 验证）",
  },
  {
    name: "东华大学·研究生院学术活动",
    url: "http://research.dhu.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学",
    defaultVenue: "东华大学",
    notes: "CALM TALK 系列 · 含 AI Agent/论文写作等前沿报告（2026-10 验证）",
  },
  {
    name: "东华大学·纺织学院学科学术报告",
    url: "http://texcol.dhu.edu.cn/xsbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学纺织学院",
    defaultVenue: "东华大学纺织学院",
    notes: "纤维材料/仿生材料方向（2026-10 验证）",
  },
  {
    name: "东华大学·信息科学与技术学院学术报告",
    url: "https://siis.dhu.edu.cn/xsbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学信息科学与技术学院",
    defaultVenue: "东华大学信息科学与技术学院",
    notes: "博学大师讲堂 / 大数据与大模型方向（2026-10 验证）",
  },
  {
    name: "东华大学·数学与统计学院学术讲座",
    url: "https://maths.dhu.edu.cn/xsjz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学数学与统计学院",
    defaultVenue: "东华大学数学与统计学院",
    notes: "极值统计等方向学术讲座（2026-10 验证）",
  },
  {
    name: "上海财经大学·经济学院学术讲座",
    url: "https://econ.sufe.edu.cn/xsjz1/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海财经大学经济学院",
    defaultVenue: "上海财经大学经济学院",
    notes: "计量/行为实验/宏观系列，标题含期号与主讲人，详情页补时间地点（2026-10 验证）",
  },
  {
    name: "上海财经大学·育衡讲坛",
    url: "https://archives.sufe.edu.cn/yhjt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海财经大学",
    defaultVenue: "上海财经大学",
    notes: "校史馆/博物馆系列公开讲坛（2026-10 验证）",
  },
  {
    name: "上海交通大学·船建学院学术活动",
    url: "https://naoce.sjtu.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海交通大学船舶海洋与建筑工程学院",
    defaultVenue: "上海交通大学船舶海洋与建筑工程学院",
    notes: "土木/船舶/力学方向报告（2026-10 验证）",
  },
  {
    name: "上海交通大学·电子信息与电气工程学院学术报告",
    url: "https://www.seiee.sjtu.edu.cn/xsbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海交通大学电子信息与电气工程学院",
    defaultVenue: "上海交通大学电子信息与电气工程学院",
    notes: "电气/自动化/计算机方向（2026-10 验证）",
  },
  {
    name: "上海理工大学·光电信息与计算机工程学院学术报告",
    url: "http://sea.usst.edu.cn/1668/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学光电信息与计算机工程学院",
    defaultVenue: "上海理工大学光电信息与计算机工程学院",
    notes: "物理人工智能等方向（2026-10 验证）",
  },
  {
    name: "上海理工大学·健康科学与工程学院学术报告",
    url: "http://jiankang.usst.edu.cn/xsbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学健康科学与工程学院",
    defaultVenue: "上海理工大学健康科学与工程学院",
    notes: "沪江大健康讲坛系列（2026-10 验证）",
  },
  {
    name: "上海理工大学·出版印刷与设计艺术学院讲座",
    url: "http://shlgwm.usst.edu.cn/jzrz_14204/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学出版印刷与设计艺术学院",
    defaultVenue: "上海理工大学出版印刷与设计艺术学院",
    notes: "光学/生物传热/固废资源化交叉学科讲座（2026-10 验证）",
  },
  {
    name: "上海理工大学·马克思主义学院学术报告",
    url: "http://mksxy.usst.edu.cn/p2753c2753/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学马克思主义学院",
    defaultVenue: "上海理工大学马克思主义学院",
    notes: "上理智造·马克思主义大讲堂（2026-10 验证）",
  },
  {
    name: "上海应用技术大学·讲座报告",
    url: "https://www.sit.edu.cn/jzbg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海应用技术大学",
    defaultVenue: "上海应用技术大学",
    notes: "列表内联讲座日期与地点（2026-10 验证）",
  },
  {
    name: "上海旅游高等专科学校·讲座报告",
    url: "https://www.sitsh.edu.cn/jzbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海旅游高等专科学校",
    defaultVenue: "上海旅游高等专科学校",
    notes: "文旅方向的公开讲座与沙龙（2026-10 验证）",
  },
  {
    name: "上海视觉艺术学院·学术活动",
    url: "https://www.siva.edu.cn/40/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海视觉艺术学院",
    defaultVenue: "上海视觉艺术学院",
    notes: "视觉沙龙系列（2026-10 验证）",
  },
  {
    name: "上海震旦职业学院·系列讲座",
    url: "https://www.aurora-college.cn/xljz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海震旦职业学院",
    defaultVenue: "上海震旦职业学院",
    notes: "民办高职讲座栏目，补全院校名单多样性（2026-10 验证）",
  },

  // ===== 2026-10 第二批扩展：高校院系讲座栏目（第二轮院系挖掘，覆盖 17 所院校）=====
  {
    name: "上海立信会计金融学院·学术讲座",
    url: "http://www.lixin.edu.cn/info/iList.jsp?cat_id=12709",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海立信会计金融学院",
    defaultVenue: "上海立信会计金融学院",
    notes: "百年百期立信会计学科高端讲坛 · JSP 列表（2026-10 验证）",
  },
  {
    name: "上海立信会计金融学院·论坛与活动",
    url: "https://gjcjxy.lixin.edu.cn/info/iList.jsp?cat_id=16000",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海立信会计金融学院国际经贸学院",
    defaultVenue: "上海立信会计金融学院国际经贸学院",
    notes: "国际经贸学院论坛与活动（2026-10 验证）",
  },
  {
    name: "上海对外经贸大学·讲座报告",
    url: "http://www.suibe.edu.cn/kyc/jzhy/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海对外经贸大学",
    defaultVenue: "上海对外经贸大学",
    notes: "【上经贸大·科研】每周学术活动预告（2026-10 验证）",
  },
  {
    name: "上海对外经贸大学·会展与传播学院学术活动",
    url: "http://www.suibe.edu.cn/sis/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海对外经贸大学会展与传播学院",
    defaultVenue: "上海对外经贸大学会展与传播学院",
    notes: "会展/传播方向学术活动（2026-10 验证）",
  },
  {
    name: "上海电机学院·航空学院讲座论坛",
    url: "http://aero.sdju.edu.cn/jzlt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海电机学院航空学院",
    defaultVenue: "上海电机学院航空学院",
    notes: "凌云公开课 · 大飞机园航空技术沙龙（2026-10 验证）",
  },
  {
    name: "上海电机学院·马克思主义学院学术活动",
    url: "http://mks.sdju.edu.cn/7633/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海电机学院马克思主义学院",
    defaultVenue: "上海电机学院马克思主义学院",
    notes: "星火讲堂系列（2026-10 验证）",
  },
  {
    name: "上海电机学院·图书馆培训讲座",
    url: "http://lib.sdju.edu.cn/8828/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海电机学院图书馆",
    defaultVenue: "上海电机学院图书馆",
    notes: "信息素养类培训讲座（2026-10 验证）",
  },
  {
    name: "上海海洋大学·研究生院学术活动",
    url: "http://yjs.shou.edu.cn/18612/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海海洋大学",
    defaultVenue: "上海海洋大学",
    notes: "研究生校级学术报告（2026-10 验证）",
  },
  {
    name: "上海第二工业大学·讲座演出",
    url: "https://education.sspu.edu.cn/354/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海第二工业大学",
    defaultVenue: "上海第二工业大学",
    notes: "「金海艺韵」艺术沙龙 · 音乐/戏剧/VR 沉浸体验，兼具演出属性（2026-10 验证）",
  },
  {
    name: "上海第二工业大学·通识大讲堂",
    url: "http://wywh.sspu.edu.cn/jzxx/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海第二工业大学",
    defaultVenue: "上海第二工业大学",
    notes: "中银-二工大通识大讲堂「半亩方塘」系列（2026-10 验证）",
  },
  {
    name: "上海第二工业大学·讲座预览",
    url: "http://zihuan.sspu.edu.cn/6110/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海第二工业大学",
    defaultVenue: "上海第二工业大学",
    notes: "环境与材料工程学院讲座预览（2026-10 验证）",
  },
  {
    name: "上海政法学院·知华讲堂",
    url: "https://iso.shupl.edu.cn/3098/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海政法学院国际交流学院",
    defaultVenue: "上海政法学院国际交流学院",
    notes: "面向留学生的知华讲堂系列（2026-10 验证）",
  },
  {
    name: "东华大学·多元文化交流坊",
    url: "https://iec.dhu.edu.cn/lectureworkshops/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学国际文化交流学院",
    defaultVenue: "东华大学国际文化交流学院",
    notes: "面向在校国际学生与公众的文化工作坊（2026-10 验证）",
  },
  {
    name: "复旦大学·旅游学系活动讲座",
    url: "https://tourism.fudan.edu.cn/xsky/hdjz.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学旅游学系",
    defaultVenue: "复旦大学旅游学系",
    notes: "MTA 精英讲座 / 旅游学研究前沿报告会（2026-10 验证）",
  },
  {
    name: "上海外国语大学·信息素养公开课",
    url: "http://lib.shisu.edu.cn/_t39/26/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海外国语大学图书馆",
    defaultVenue: "上海外国语大学图书馆",
    notes: "90 分钟信息素养公开课 · AI 检索/编程主题，面向公众开放（2026-10 验证）",
  },
  {
    name: "上海理工大学·沪江格致论坛",
    url: "http://chxy.usst.edu.cn/jzlt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学材料与化学学院",
    defaultVenue: "上海理工大学材料与化学学院",
    notes: "青年学者研讨会 / 期刊校园巡回讲座，标题内联日期（2026-10 验证）",
  },
  {
    name: "上海理工大学·管理学院科研讲座",
    url: "http://bs.usst.edu.cn/kyjz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海理工大学管理学院",
    defaultVenue: "上海理工大学管理学院",
    notes: "优化算法/物流网络/集群机器人等方向（2026-10 验证）",
  },
  {
    name: "上海海事大学·学术讲座（英文站）",
    url: "https://en.shmtu.edu.cn/Events/list.htm",
    category: "高校讲座",
    locale: "en",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海海事大学",
    defaultVenue: "上海海事大学",
    notes: "英文站 Events · 国际培训项目与学术活动（2026-10 验证）",
  },

  // ===== 2026-10 第二批扩展：Eventbrite 上海细分类别 =====
  { name: "Eventbrite 上海·舞蹈", url: "https://www.eventbrite.com/d/china--shanghai/dance--events/", category: "演出音乐", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·古典音乐", url: "https://www.eventbrite.com/d/china--shanghai/classical--events/", category: "演出音乐", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·爵士", url: "https://www.eventbrite.com/d/china--shanghai/jazz--events/", category: "演出音乐", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·戏剧", url: "https://www.eventbrite.com/d/china--shanghai/theatre--events/", category: "演出音乐", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·读书", url: "https://www.eventbrite.com/d/china--shanghai/book--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·文化", url: "https://www.eventbrite.com/d/china--shanghai/cultural--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·在线活动", url: "https://www.eventbrite.com/d/china--shanghai/online--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·工作坊", url: "https://www.eventbrite.com/d/china--shanghai/workshop--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·展览", url: "https://www.eventbrite.com/d/china--shanghai/exhibitions-and-shows--events/", category: "展览", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·设计", url: "https://www.eventbrite.com/d/china--shanghai/design--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·游戏", url: "https://www.eventbrite.com/d/china--shanghai/gaming--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·免费", url: "https://www.eventbrite.com/d/china--shanghai/free--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },

  {
    name: "上海建桥学院·百家讲坛",
    url: "https://www.gench.edu.cn/bjjt_13038/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海建桥学院",
    defaultVenue: "上海建桥学院",
    notes: "列表摘要内嵌讲座时间/地点/主办单位（2026-10 验证）",
  },
  {
    name: "上海大学·学术讲座（英文站）",
    url: "http://en.shu.edu.cn/events/index",
    category: "高校讲座",
    locale: "en",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海大学",
    defaultVenue: "上海大学",
    notes: "上大英文站 Lecture/Event 栏目 · 面向国际学者的数学/信息/材料报告（2026-10 验证）",
  },
  {
    name: "上海社会科学院·学术活动",
    url: "https://www.sass.org.cn/",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海社会科学院",
    defaultVenue: "上海社会科学院",
    notes: "智库专家公开报告（经济/城乡/国际议题）（2026-10 验证）",
  },

  // ===== 2026-10 扩展：演出音乐 =====
  {
    name: "上海古典音乐会·上海乐历",
    url: "https://shanghaiconcerts.com/concerts",
    category: "演出音乐",
    locale: "zh",
    parser: PARSERS.shanghaiConcerts,
    notes: "SSR 演出日历 · 未来 30 天古典音乐/歌剧/音乐剧，含场馆与开演时间（2026-10 新增，含专用解析器）",
  },

  // ===== 2026-10 扩展：豆瓣同城子类目（父源综合榜覆盖不到的漏网条目）=====
  { name: "豆瓣同城·上海戏剧", url: "https://www.douban.com/location/shanghai/events/week-drama", category: "演出音乐", locale: "zh", parser: PARSERS.douban },
  { name: "豆瓣同城·上海音乐", url: "https://www.douban.com/location/shanghai/events/week-music", category: "演出音乐", locale: "zh", parser: PARSERS.douban },
  { name: "豆瓣同城·上海展览", url: "https://www.douban.com/location/shanghai/events/week-exhibition", category: "展览", locale: "zh", parser: PARSERS.douban },
  { name: "豆瓣同城·上海讲座沙龙", url: "https://www.douban.com/location/shanghai/events/week-salon", category: "线下活动", locale: "zh", parser: PARSERS.douban },
  { name: "豆瓣同城·上海聚会", url: "https://www.douban.com/location/shanghai/events/week-party", category: "线下活动", locale: "zh", parser: PARSERS.douban },
  { name: "豆瓣同城·上海公益", url: "https://www.douban.com/location/shanghai/events/week-commonweal", category: "线下活动", locale: "zh", parser: PARSERS.douban },
  { name: "豆瓣同城·上海电影", url: "https://www.douban.com/location/shanghai/events/week-film", category: "线下活动", locale: "zh", parser: PARSERS.douban },

  // ===== 2026-10 扩展：Eventbrite 上海细分频道（父源综合榜漏掉的长期收录项）=====
  { name: "Eventbrite 上海·语言交流", url: "https://www.eventbrite.com/d/china--shanghai/languages--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·兴趣爱好", url: "https://www.eventbrite.com/d/china--shanghai/hobbies-and-special-interest--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·表演与视觉艺术", url: "https://www.eventbrite.com/d/china--shanghai/performing-and-visual-arts--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·美食饮品", url: "https://www.eventbrite.com/d/china--shanghai/food-and-drink--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·健康身心", url: "https://www.eventbrite.com/d/china--shanghai/health--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·时尚", url: "https://www.eventbrite.com/d/china--shanghai/fashion--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },
  { name: "Eventbrite 上海·社区", url: "https://www.eventbrite.com/d/china--shanghai/community--events/", category: "线下活动", locale: "en", parser: PARSERS.tentimes },

  // ===== 2026-10 扩展：活动行上海细分标签 =====
  {
    name: "活动行·上海读书会",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E8%AF%BB%E4%B9%A6%E4%BC%9A",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.huodong,
  },
  {
    name: "活动行·上海机器人",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E6%9C%BA%E5%99%A8%E4%BA%BA",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "具身智能/机器人开发者活动",
  },
  {
    name: "活动行·上海创业投资",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=%E5%88%9B%E4%B8%9A%E6%8A%95%E8%B5%84",
    category: "线下活动",
    locale: "zh",
    parser: PARSERS.huodong,
    notes: "路演/创投对接会",
  },
  {
    name: "活动行·上海Web3",
    url: "https://www.huodongxing.com/eventlist?city=%E4%B8%8A%E6%B5%B7&tag=Web3",
    category: "AI聚会",
    locale: "zh",
    parser: PARSERS.huodong,
  },
  // ===== 2026-10 第三批扩展：院系讲座栏目再挖掘（复旦/同济/东华/华东师大/上海商学院等）=====
  {
    name: "复旦大学·历史学系学术动态",
    url: "http://history.fudan.edu.cn/xsky/xsdt.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学历史学系",
    defaultVenue: "复旦大学历史学系",
    notes: "史学动态栏目 · 含讲座/学术活动预告（2026-10 验证）",
  },
  {
    name: "复旦大学·中文系学术活动",
    url: "http://chinese.fudan.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学中文系",
    defaultVenue: "复旦大学中文系",
    notes: "复旦中文系·学术活动栏目（2026-10 验证）",
  },
  {
    name: "复旦大学·经济学院学术前沿",
    url: "http://www.econ.fudan.edu.cn/xwzx/xsqy.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学经济学院",
    defaultVenue: "复旦大学经济学院",
    notes: "经济学院·学术前沿栏目（2026-10 验证）",
  },
  {
    name: "复旦大学·经济活动预告",
    url: "http://www.econ.fudan.edu.cn/xyfw1/hdyg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学经济学院",
    defaultVenue: "复旦大学经济学院",
    notes: "经济学院·校园服务活动预告（2026-10 验证）",
  },
  {
    name: "复旦大学·管理学院讲座信息",
    url: "https://sme.fudan.edu.cn/29432/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学管理学院",
    defaultVenue: "复旦大学管理学院",
    notes: "管院·讲座信息栏目（2026-10 验证）",
  },
  {
    name: "复旦大学·大气与海洋系学术报告",
    url: "https://aos.fudan.edu.cn/xsbg_14896/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学大气与海洋科学系",
    defaultVenue: "复旦大学大气与海洋科学系",
    notes: "大气与海洋系·学术报告（2026-10 验证）",
  },
  {
    name: "复旦大学·航空航天系光华青年学者论坛",
    url: "https://aero-mech.fudan.edu.cn/ghqnxzlt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学航空航天系",
    defaultVenue: "复旦大学航空航天系",
    notes: "光华青年学者论坛（2026-10 验证）",
  },
  {
    name: "复旦大学·英文站 Events",
    url: "http://www.fudan.edu.cn/en/Events/list.htm",
    category: "高校讲座",
    locale: "en",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学",
    defaultVenue: "复旦大学",
    notes: "复旦英文站 Lecture/Event 栏目（2026-10 验证）",
  },
  {
    name: "复旦大学·教育发展基金会讲座公示",
    url: "https://fuedf.fudan.edu.cn/jzgs/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "复旦大学教育发展基金会",
    defaultVenue: "复旦大学教育发展基金会",
    notes: "基金会·讲座公示栏目（2026-10 验证）",
  },
  {
    name: "同济大学·教育基金会讲座档案",
    url: "http://fund.tongji.edu.cn/jzda_37564/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "同济大学教育基金会",
    defaultVenue: "同济大学教育基金会",
    notes: "基金会·讲座档案（2026-10 验证）",
  },
  {
    name: "同济大学·国际学术论坛",
    url: "http://gs.tongji.edu.cn/gjjl/gjxslt.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "同济大学研究生院",
    defaultVenue: "同济大学研究生院",
    notes: "研究生院·国际学术论坛（2026-10 验证）",
  },
  {
    name: "同济大学·嘉定校区讲座论坛",
    url: "https://jiading.tongji.edu.cn/jzlt_5668/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "同济大学嘉定校区",
    defaultVenue: "同济大学嘉定校区",
    notes: "嘉定校区·讲座论坛（2026-10 验证）",
  },
  {
    name: "东华大学·物理系学术活动",
    url: "https://phys.dhu.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学物理系",
    defaultVenue: "东华大学物理系",
    notes: "物理系·学术活动（2026-10 验证）",
  },
  {
    name: "东华大学·外语学院学术动态",
    url: "http://flc.dhu.edu.cn/3313/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学外语学院",
    defaultVenue: "东华大学外语学院",
    notes: "外语学院·学术动态（2026-10 验证）",
  },
  {
    name: "东华大学·材料学院学术报告",
    url: "http://cmse.dhu.edu.cn/xsbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "东华大学材料科学与工程学院",
    defaultVenue: "东华大学材料科学与工程学院",
    notes: "材料学院·学术报告（2026-10 验证）",
  },
  {
    name: "华东师范大学·人文社会科学研究院学术活动",
    url: "https://rwsk.ecnu.edu.cn/25043/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "华东师范大学人文社会科学研究院",
    defaultVenue: "华东师范大学人文社会科学研究院",
    notes: "人文社科研究院·学术活动（2026-10 验证）",
  },
  {
    name: "上海商学院·学术论坛",
    url: "https://jxzt.sbs.edu.cn/jjss/xslt/index.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海商学院",
    defaultVenue: "上海商学院",
    notes: "上海商学院·学术论坛栏目（2026-10 验证，补全未覆盖院校）",
  },

  // ===== 2026-10 第四批扩展：上海科技大学各院所 + 复旦/同济/东华/华师外的院校院系栏目再挖掘 =====
  {
    name: "上海科技大学·信息学院学术活动",
    url: "http://siais.shanghaitech.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学信息学院",
    defaultVenue: "上海科技大学信息学院",
    notes: "上科大信息学院·学术活动通知（2026-10 验证）",
  },
  {
    name: "上海科技大学·创业学院讲座活动",
    url: "http://sem.shanghaitech.edu.cn/372/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学创业学院",
    defaultVenue: "上海科技大学创业学院",
    notes: "创管学院·讲座活动（2026-10 验证）",
  },
  {
    name: "上海科技大学·创业学院讲座与活动预告",
    url: "http://sem.shanghaitech.edu.cn/gkjz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学创业学院",
    defaultVenue: "上海科技大学创业学院",
    notes: "创管学院·讲座与活动预告（2026-10 验证）",
  },
  {
    name: "上海科技大学·物质科学与技术学院 seminar",
    url: "http://spst.shanghaitech.edu.cn/seminar/list.htm",
    category: "高校讲座",
    locale: "en",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学物质科学与技术学院",
    defaultVenue: "上海科技大学物质科学与技术学院",
    notes: "物质学院·学院活动/seminar（2026-10 验证）",
  },
  {
    name: "上海科技大学·人文研究院学术报告",
    url: "https://ihuman.shanghaitech.edu.cn/xsbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学人文研究院",
    defaultVenue: "上海科技大学人文研究院",
    notes: "人文研究院·学术报告（2026-10 验证）",
  },
  {
    name: "上海科技大学·创意与艺术学院学术活动",
    url: "https://cts.shanghaitech.edu.cn/xshd1/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学创意与艺术学院",
    defaultVenue: "上海科技大学创意与艺术学院",
    notes: "创意与艺术学院·学术活动（2026-10 验证）",
  },
  {
    name: "上海科技大学·创意与艺术学院科普讲座",
    url: "https://cts.shanghaitech.edu.cn/kpjz_8540/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学创意与艺术学院",
    defaultVenue: "上海科技大学创意与艺术学院",
    notes: "创意与艺术学院·科普讲座（2026-10 验证）",
  },
  {
    name: "上海科技大学·生物医学工程学院学术讲座",
    url: "https://bme.shanghaitech.edu.cn/xsjz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学生物医学工程学院",
    defaultVenue: "上海科技大学生物医学工程学院",
    notes: "生医工学院·学术讲座（2026-10 验证）",
  },
  {
    name: "上海科技大学·信息学院卓越讲座",
    url: "http://sist.shanghaitech.edu.cn/zyjz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海科技大学信息学院",
    defaultVenue: "上海科技大学信息学院",
    notes: "信息学院·卓越讲座系列（2026-10 验证）",
  },
  {
    name: "上海对外经贸大学·法学院学术活动",
    url: "https://www.suibe.edu.cn/fxy/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海对外经贸大学法学院",
    defaultVenue: "上海对外经贸大学法学院",
    notes: "法学院·学术活动（2026-10 验证）",
  },
  {
    name: "上海第二工业大学·学术活动",
    url: "https://sic.sspu.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海第二工业大学",
    defaultVenue: "上海第二工业大学",
    notes: "sic 栏目·学术活动（2026-10 验证）",
  },
  {
    name: "上海第二工业大学·活动预告",
    url: "http://jxxy.sspu.edu.cn/2069/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海第二工业大学",
    defaultVenue: "上海第二工业大学",
    notes: "jxxy 栏目·活动预告（2026-10 验证）",
  },
  {
    name: "上海第二工业大学·学生活动",
    url: "http://jxxy.sspu.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    venueLabel: "上海第二工业大学",
    defaultVenue: "上海第二工业大学",
    notes: "jxxy 栏目·学生活动（2026-10 验证）",
  },

  // ===== 2026-10 第五批扩展：院系讲座/通知公告栏目再挖掘（复旦/华师/上师大/上理工/东华/上财/同济/华政/上大/上海海关学院/上海工商外职院）=====
  {
    name: "复旦中文系·通知公告",
    url: "http://chinese.fudan.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 9/13)",
  },
  {
    name: "华师本科生院·通知公告(吾校生活)",
    url: "https://bksy.ecnu.edu.cn/tzggwwxsgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 9/9)",
  },
  {
    name: "上师大·学术信息",
    url: "https://www.shnu.edu.cn/_s3/_t774/xsxx/list.psp",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 7/14)",
  },
  {
    name: "复旦化学系·通知公告",
    url: "http://www.chm.fudan.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 5/13)",
  },
  {
    name: "上理工机械学院·通知公告",
    url: "http://me.usst.edu.cn/tzgg_12289/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 4/4)",
  },
  {
    name: "华师本科生院·通知公告(教师发展)",
    url: "https://bksy.ecnu.edu.cn/tzggwwjslm/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 3/12)",
  },
  {
    name: "复旦化学系·百年学术报告",
    url: "http://www.chemistry.fudan.edu.cn/45207/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 2/14)",
  },
  {
    name: "上师大教育学院·通知公告",
    url: "http://shidao.shnu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 1/14)",
  },
  {
    name: "上大继续教育·学历教育通知",
    url: "https://cce.shu.edu.cn/xljy/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 1/3)",
  },
  {
    name: "上大继续教育·通知公告",
    url: "https://cce.shu.edu.cn/symk/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 1/3)",
  },
  {
    name: "华政·通知公告",
    url: "http://www.ecupl.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 1/1)",
  },
  {
    name: "东华教务处·通知公告",
    url: "http://jw.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 1/1)",
  },
  {
    name: "东华·通知公告",
    url: "https://wkc.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·窗口内活跃(召回 1/1)",
  },
  {
    name: "东华·通知公告",
    url: "http://cbm.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 20 条，近期无更新)",
  },
  {
    name: "上财校史馆·会议论坛",
    url: "https://archives.sufe.edu.cn/hylt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 20 条，近期无更新)",
  },
  {
    name: "上海海关学院·学术活动",
    url: "https://flx.shcc.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 20 条，近期无更新)",
  },
  {
    name: "上理工·学习活动",
    url: "http://bs.usst.edu.cn/hdkz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 16 条，近期无更新)",
  },
  {
    name: "上理工·活动通知",
    url: "http://bs.usst.edu.cn/hdtz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 14 条，近期无更新)",
  },
  {
    name: "同济·通知公告",
    url: "https://tjwm.tongji.edu.cn/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 14 条，近期无更新)",
  },
  {
    name: "复旦化学系·学术活动",
    url: "http://www.chm.fudan.edu.cn/xshd/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 14 条，近期无更新)",
  },
  {
    name: "上海海关学院·海关法论坛",
    url: "https://flx.shcc.edu.cn/hgfyjzx/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 12 条，近期无更新)",
  },
  {
    name: "上师大图书馆·活动聚焦",
    url: "https://lib.shnu.edu.cn/hdjj/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 11 条，近期无更新)",
  },
  {
    name: "上师大教学发展中心·教学发展沙龙",
    url: "https://jxfz.shnu.edu.cn/jxfzsl/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 10 条，近期无更新)",
  },
  {
    name: "复旦上海医学院·通知公告",
    url: "https://shmc.fudan.edu.cn/news/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 9 条，近期无更新)",
  },
  {
    name: "东华·通知公告",
    url: "http://ictst.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 8 条，近期无更新)",
  },
  {
    name: "东华·活动公告",
    url: "http://fzys.dhu.edu.cn/hdgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 8 条，近期无更新)",
  },
  {
    name: "上大研究生院·招生培养通知",
    url: "https://yjszs.shu.edu.cn/cd/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 8 条，近期无更新)",
  },
  {
    name: "东华马克思主义学院·通知公告",
    url: "http://marx.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 8 条，近期无更新)",
  },
  {
    name: "上理工研究生院·通知公告",
    url: "http://yjs.usst.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 8 条，近期无更新)",
  },
  {
    name: "复旦航空航天系·通知公告",
    url: "https://aero-mech.fudan.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 8 条，近期无更新)",
  },
  {
    name: "上财科研处·学者论坛",
    url: "https://ky.sufe.edu.cn/scwxzwxwwxpwlt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 8 条，近期无更新)",
  },
  {
    name: "同济研究生院·通知公告",
    url: "http://gs.tongji.edu.cn/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 7 条，近期无更新)",
  },
  {
    name: "上财教务处·通知公告",
    url: "https://jiaoxue.sufe.edu.cn/index/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 7 条，近期无更新)",
  },
  {
    name: "东华材料学院·通知公告",
    url: "http://cmse.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 6 条，近期无更新)",
  },
  {
    name: "上理工·教学沙龙",
    url: "http://cftd.usst.edu.cn/jxsl/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 6 条，近期无更新)",
  },
  {
    name: "上理工·发展论坛",
    url: "http://cftd.usst.edu.cn/fzrt/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 6 条，近期无更新)",
  },
  {
    name: "上师大教学发展中心·讲座",
    url: "https://jxfz.shnu.edu.cn/jzbg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 6 条，近期无更新)",
  },
  {
    name: "上海工商外职院·讲座",
    url: "https://dsw.sicfl.edu.cn/jz/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 6 条，近期无更新)",
  },
  {
    name: "东华·通知公告",
    url: "http://inforcenter.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 5 条，近期无更新)",
  },
  {
    name: "上师大·活动预告",
    url: "https://www.shnu.edu.cn/_s3/_t774/hdyc/list.psp",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 5 条，近期无更新)",
  },
  {
    name: "上理工·通知公告",
    url: "https://glhospital.usst.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 5 条，近期无更新)",
  },
  {
    name: "同济国际事务·港澳台事务",
    url: "http://fao.tongji.edu.cn/gatsw/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 4 条，近期无更新)",
  },
  {
    name: "上理工·通知公告",
    url: "http://cftd.usst.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 4 条，近期无更新)",
  },
  {
    name: "上师大教育学院·师德论坛",
    url: "http://shidao.shnu.edu.cn/xsfy/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 4 条，近期无更新)",
  },
  {
    name: "同济嘉定·活动预告",
    url: "https://jiading.tongji.edu.cn/hdyg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 3 条，近期无更新)",
  },
  {
    name: "东华·通知公告",
    url: "http://ico.dhu.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 3 条，近期无更新)",
  },
  {
    name: "华师·通知公告",
    url: "https://zizhu.ecnu.edu.cn/tzgg_41428/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 2 条，近期无更新)",
  },
  {
    name: "上理工双创·通知公告",
    url: "http://cxcy.usst.edu.cn/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 2 条，近期无更新)",
  },
  {
    name: "上理工双创·通知公告",
    url: "http://cxcy.usst.edu.cn/_t2377/tzgg/list.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 2 条，近期无更新)",
  },
  {
    name: "上大·招生培养通知",
    url: "https://global.shu.edu.cn/cd/tzgg.htm",
    category: "高校讲座",
    locale: "zh",
    parser: PARSERS.cnCmsLectures,
    notes: "第五批扩展·已验证栏目(近 2 条，近期无更新)",
  },

  ...(process.env.WECHAT_EVENTS_API_URL || process.env.WECHAT_EXPORTER_AUTH_KEY
    ? [
        {
          name: "微信公众号活动",
          url: process.env.WECHAT_EVENTS_API_URL || process.env.WECHAT_EXPORTER_BASE_URL || "http://localhost:3001",
          category: process.env.WECHAT_DEFAULT_CATEGORY || "线下活动",
          locale: "zh",
          parser: PARSERS.wechat,
          timeoutMs: 180_000,
        },
      ]
    : []),

  // X（Twitter）账号时间线：仅当同时配置 X_BEARER_TOKEN 与 X_SHANGHAI_ACCOUNTS 时注册。
  // 注意 api.x.com 在境内不可达，需把采集跑在境外出口的环境（见 x-timeline.js 注释）。
  ...(process.env.X_BEARER_TOKEN && process.env.X_SHANGHAI_ACCOUNTS
    ? String(process.env.X_SHANGHAI_ACCOUNTS)
        .split(",")
        .map((handle) => handle.trim())
        .filter(Boolean)
        .map((handle) => ({
          name: `X @${handle}`,
          url: `https://x.com/${handle}`,
          category: process.env.X_DEFAULT_CATEGORY || "线下活动",
          locale: "en",
          parser: PARSERS.xTimeline,
          xHandle: handle,
          defaultVenue: "上海",
        }))
    : []),
];

const T1_VENUE_NAMES = new Set([
  "teamLab 无界上海",
  "UCCA Edge 上海",
  "Fotografiska 上海",
  "AI Tinkerers Shanghai",
]);
const T1_NAME_PATTERNS = [/美术馆|博物馆|艺术宫|艺术中心|剧院|文化广场/];
const T2_NAME_PATTERNS = [/豆瓣|SmartShanghai|AllEvents|Eventbrite|iMuseum|赢商网|Timeout|上海热线|活动行|互动吧|Lu\.?ma|格瓦拉|票牛|Meetup/i];

export function resolveSourceTier(source) {
  if (source?.tier) return source.tier;
  const name = source?.name || "";
  const url = source?.url || "";
  if (/\.edu\.cn(\/|$)/i.test(url) || /nyu\.edu/i.test(url)) return "T1";
  if (/\.gov\.cn(\/|$)/i.test(url)) return "T1";
  if (T1_VENUE_NAMES.has(name)) return "T1";
  if (T1_NAME_PATTERNS.some((re) => re.test(name))) return "T1";
  if (T2_NAME_PATTERNS.some((re) => re.test(name))) return "T2";
  return "T2";
}

// 停采清单（2026-10-01）：以下 40 个信源在当前采集 runner（腾讯云 124.223.200.89，上海电信）
// 网络上已确认零召回——不是解析规则问题，是网络出口/源站策略问题，逐源实测结论：
//   · Eventbrite 全系 25 源：HTTP 405，机房 IP 被反爬拦截（换 UA/Referer、强制 HTTP/1.1、HTTP/2 均无效）
//   · 活动行系 10 源：HTTP 403。注意断点很新（2026-09-27 起，此前连续 18 次采集正常），
//     同期 AllEvents / Lu.ma 也一起断——疑似 runner 出口 IP 被限，属可恢复项，建议 1~2 周后复查
//   · AllEvents Shanghai：HTTP 403；Lu.ma Shanghai：ETIMEDOUT
//   · 上海热线：HTTP 412 反爬；苏州博物馆：源站返回畸形 HTTP 头，Node 解析器拒绝
//     （HPE_INVALID_HEADER_TOKEN，insecureHTTPParser 也救不回）
//   · NYU Shanghai Events：证书链缺中间证书（UNABLE_TO_VERIFY_LEAF_SIGNATURE，--use-system-ca 无效）
// 恢复方式：从下面的集合里删掉对应名字即可，上方的 URL 与 parser 定义都还在。
const RETIRED_SOURCE_NAMES = new Set([
  "AllEvents Shanghai",
  "Eventbrite Shanghai",
  "Eventbrite Shanghai Music",
  "Eventbrite Shanghai Business",
  "Eventbrite Shanghai Networking",
  "Eventbrite Shanghai AI",
  "Eventbrite Shanghai Tech",
  "Eventbrite 上海·舞蹈",
  "Eventbrite 上海·古典音乐",
  "Eventbrite 上海·爵士",
  "Eventbrite 上海·戏剧",
  "Eventbrite 上海·读书",
  "Eventbrite 上海·文化",
  "Eventbrite 上海·在线活动",
  "Eventbrite 上海·工作坊",
  "Eventbrite 上海·展览",
  "Eventbrite 上海·设计",
  "Eventbrite 上海·游戏",
  "Eventbrite 上海·免费",
  "Eventbrite 上海·语言交流",
  "Eventbrite 上海·兴趣爱好",
  "Eventbrite 上海·表演与视觉艺术",
  "Eventbrite 上海·美食饮品",
  "Eventbrite 上海·健康身心",
  "Eventbrite 上海·时尚",
  "Eventbrite 上海·社区",
  "活动行上海",
  "活动行·上海推荐",
  "活动行·上海AI",
  "活动行·上海AI关键词",
  "活动行·上海大模型",
  "活动行·上海AIGC",
  "活动行·上海读书会",
  "活动行·上海机器人",
  "活动行·上海创业投资",
  "活动行·上海Web3",
  "上海热线",
  "苏州博物馆",
  "NYU Shanghai Events",
  "Lu.ma Shanghai",

  // 域名没错、也没被反爬——是**领域不对**，与上面那批（网络/反爬）原因不同，特此分开记。
  // 赢商网是商业地产门户，整站产出的是「新店开业 / 品牌首店 / 招商盘点」资讯，不是活动。
  // 更糟的是它的条目拿不到场馆，buildEvent 会把 venue 兜底成"上海"，
  // 于是连 isShanghaiRelevantEvent 都拦不住——2026-10 实测窗口内外共 16 条全部是
  // 广州/深圳/武汉/昆明/山东/长沙的项目资讯，成了「线下活动」里最大的一坨噪声。
  // 通用兜底已写进 events.js 的 NEWS_TITLE_PATTERNS（待开业/首店/商业项目），
  // 但这条源本身没有有效产出，直接退休。恢复方式：从集合里删掉即可。
  "赢商网",
  "赢商网·华东",
]);

export const SOURCE_SEEDS = SOURCE_SEEDS_RAW
  .filter((source) => !RETIRED_SOURCE_NAMES.has(source.name))
  .map((source) => ({
    ...source,
    tier: resolveSourceTier(source),
  }));

// 失败原因分类：把原始错误字符串归入固定桶，供健康报告做可靠的趋势统计
// （替代之前 health-check 里 String(msg).split(':')[0] 的脆弱字符串前缀匹配）。
export function classifyFailure(message) {
  const text = String(message || "");
  if (/timed?\s*out|超时|after \d+s/i.test(text)) return "timeout";
  if (/429/.test(text)) return "rate_limited";
  if (/HTTP\s*4\d\d|HTTP 4\d\d/.test(text)) return "http_4xx";
  if (/HTTP\s*5\d\d|HTTP 5\d\d/.test(text)) return "http_5xx";
  if (/fetch failed|ENOTFOUND|ECONNRESET|ECONNREFUSED|EAI_AGAIN|getaddrinfo|TypeError|cert|ssl/i.test(text)) return "network";
  if (/parse|解析|JSON|无法|expected|unexpected token/i.test(text)) return "parse";
  return "unknown";
}

async function withSourceTimeout(task, sourceName, timeoutMs) {
  let timer;
  try {
    return await Promise.race([
      task(),
      new Promise((_, reject) => {
        timer = setTimeout(() => reject(new Error(`${sourceName} timed out after ${timeoutMs / 1000}s`)), timeoutMs);
      }),
    ]);
  } finally {
    clearTimeout(timer);
  }
}

// 有界并发度：与 source-health-check.js 的 CONCURRENCY 对齐。
// 这些源都是不同网站，并发 5 不会触发反爬；慢源/超时不再拖垮整批采集时长。
const DEFAULT_CONCURRENCY = Number(process.env.COLLECTOR_CONCURRENCY) || 5;

export async function collectEventsFromSources({
  sources = SOURCE_SEEDS,
  previousEvents = [],
  fetchHtml = defaultFetchHtml,
  now = new Date(),
  concurrency = DEFAULT_CONCURRENCY,
  respectRobots = process.env.COLLECTOR_RESPECT_ROBOTS !== "false",
} = {}) {
  const { startDate, endDate, days } = toShanghaiDayWindow(now);
  const failures = [];
  const collected = [];
  const robotsSkipped = [];

  const collectOne = async (source) => {
    // robots 闸门：站点明示禁止抓取时跳过，记入 skipped 而非 failures，
    // 避免健康报告把「被 robots 拒绝」误判成「源已失效」。
    if (respectRobots) {
      try {
        const decision = await checkRobots(source.url);
        if (!decision.allowed) {
          return {
            events: [],
            failure: null,
            skipped: { source: source.name, url: source.url, reason: decision.reason || "robots_disallow" },
          };
        }
      } catch {
        // 闸门自身异常不应阻断采集
      }
    }
    try {
      const parsed = await withSourceTimeout(
        async () => {
          const html = await fetchHtml(source.url);
          return source.parser(html, source, { fetchHtml, now, window: { startDate, endDate, days } });
        },
        source.name,
        source.timeoutMs || 45_000,
      );
      return { events: parsed, failure: null };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        events: [],
        failure: {
          source: source.name,
          url: source.url,
          message,
          kind: classifyFailure(message),
        },
      };
    }
  };

  const limit = Math.max(1, concurrency);
  for (let index = 0; index < sources.length; index += limit) {
    const chunk = sources.slice(index, index + limit);
    const outcomes = await Promise.all(chunk.map(collectOne));
    for (const outcome of outcomes) {
      if (outcome.failure) failures.push(outcome.failure);
      else if (outcome.skipped) robotsSkipped.push(outcome.skipped);
      else collected.push(...outcome.events);
    }
  }

  const events = mergeDuplicateEvents(
    filterPublishableEvents(collected)
      .filter((event) => isInDateRange(event, startDate, endDate))
      .filter((event) => event.category !== "演出音乐" || isRelevantPerformance(event)),
  );

  if (events.length === 0 && previousEvents.length > 0) {
    return {
      ok: false,
      events: previousEvents,
      failures,
      robotsSkipped,
      collectedCount: 0,
      publishedCount: previousEvents.length,
      startDate,
      endDate,
      windowDays: days,
      lastUpdatedAt: new Date().toISOString(),
    };
  }

  return {
    ok: failures.length === 0,
    events,
    failures,
    robotsSkipped,
    rawEvents: collected,
    collectedCount: collected.length,
    publishedCount: events.length,
    startDate,
    endDate,
    windowDays: days,
    lastUpdatedAt: new Date().toISOString(),
  };
}
