function event({
  title,
  day,
  time,
  venue,
  category,
  url,
  source,
  key,
}) {
  return {
    title,
    start_time: `2026-05-${day}T${time}:00+08:00`,
    end_time: null,
    venue,
    category,
    signup_url: url,
    source_name: source,
    source_url: url,
    dedupe_key: key,
    sources: [{ name: source, url }],
  };
}

export const SAMPLE_EVENTS = [
  event({
    title: "上海城市周末爵士现场",
    day: "22",
    time: "20:00",
    venue: "Blue Note Shanghai",
    category: "演出音乐",
    url: "https://show.maoyan.com/",
    source: "猫眼演出",
    key: "sample-jazz",
  }),
  event({
    title: "独立乐队夜：新声专场",
    day: "22",
    time: "21:00",
    venue: "育音堂音乐公园",
    category: "演出音乐",
    url: "https://www.smartshanghai.com/events/",
    source: "SmartShanghai Events",
    key: "sample-indie-night",
  }),
  event({
    title: "周六开放麦脱口秀",
    day: "23",
    time: "19:30",
    venue: "南京东路喜剧空间",
    category: "演出音乐",
    url: "https://huodong.com/shanghai",
    source: "活动网上海",
    key: "sample-standup",
  }),
  event({
    title: "室内乐四重奏音乐会",
    day: "24",
    time: "15:00",
    venue: "上海音乐厅",
    category: "演出音乐",
    url: "https://show.maoyan.com/",
    source: "猫眼演出",
    key: "sample-chamber",
  }),
  event({
    title: "当代摄影开放展",
    day: "23",
    time: "10:00",
    venue: "Fotografiska Shanghai",
    category: "展览",
    url: "https://shanghai.fotografiska.com/en/whats-on",
    source: "Fotografiska Shanghai",
    key: "sample-photo",
  }),
  event({
    title: "外滩当代艺术现场",
    day: "22",
    time: "11:00",
    venue: "上海外滩美术馆",
    category: "展览",
    url: "https://www.rockbundartmuseum.org/",
    source: "上海外滩美术馆",
    key: "sample-rockbund",
  }),
  event({
    title: "沉浸式数字艺术展",
    day: "24",
    time: "10:30",
    venue: "teamLab 无界上海",
    category: "展览",
    url: "https://art.team-lab.cn/e/borderless-shanghai/",
    source: "teamLab 无界上海",
    key: "sample-teamlab",
  }),
  event({
    title: "城市设计与潮流生活展",
    day: "21",
    time: "14:00",
    venue: "上海展览中心",
    category: "展览",
    url: "https://10times.com/shanghai-cn",
    source: "10times Shanghai",
    key: "sample-design-expo",
  }),
  event({
    title: "周末咖啡生活节",
    day: "24",
    time: "11:00",
    venue: "上海",
    category: "线下活动",
    url: "https://whlyj.sh.gov.cn/",
    source: "上海文旅局",
    key: "sample-coffee",
  }),
  event({
    title: "春夏手作集市",
    day: "23",
    time: "13:00",
    venue: "静安大悦城",
    category: "线下活动",
    url: "https://allevents.in/shanghai",
    source: "AllEvents Shanghai",
    key: "sample-market",
  }),
  event({
    title: "城市骑行友好赛",
    day: "24",
    time: "08:30",
    venue: "徐汇滨江",
    category: "线下活动",
    url: "https://www.shanghai.gov.cn/",
    source: "上海发布活动",
    key: "sample-cycling",
  }),
  event({
    title: "家居生活方式开放日",
    day: "22",
    time: "10:00",
    venue: "上海世博展览馆",
    category: "线下活动",
    url: "https://10times.com/shanghai-cn",
    source: "10times Shanghai",
    key: "sample-home",
  }),
  event({
    title: "AI 与城市研究公开讲座",
    day: "21",
    time: "19:00",
    venue: "NYU Shanghai",
    category: "高校讲座",
    url: "https://events.shanghai.nyu.edu/",
    source: "NYU Shanghai Events",
    key: "sample-talk",
  }),
  event({
    title: "AI 未来：技术封建主义，还是新范式？",
    day: "22",
    time: "18:30",
    venue: "上海交通大学",
    category: "高校讲座",
    url: "https://www.sipa.sjtu.edu.cn/show/6774",
    source: "上海交通大学国际与公共事务学院",
    key: "sample-sjtu-ai",
  }),
  event({
    title: "设计大家谈：平面设计对流",
    day: "23",
    time: "14:00",
    venue: "上海交通大学设计学院",
    category: "高校讲座",
    url: "https://designschool.sjtu.edu.cn/",
    source: "上海交通大学设计学院",
    key: "sample-design-talk",
  }),
  event({
    title: "跨文化传播与城市记忆论坛",
    day: "24",
    time: "10:00",
    venue: "上外松江校区",
    category: "高校讲座",
    url: "https://event.shisu.edu.cn/",
    source: "上外活动平台",
    key: "sample-sisu-forum",
  }),
];
